###
GET http://localhost:3000/clients/

//Mostrar por RFC #poner un RFC
###
GET http://localhost:3000/clients/hola

//Crear Cliente
###
POST http://localhost:3000/clients/
Content-Type: application/json

{
 "rfc": "hola",
  "first_name": "xxx",
  "last_name": "xxx",
  "birth_date": "1990-05-20",
  "gender": "M",
  "phone_number": "5551234567",
  "email": "xxx@xxx.com",
  "address": "xxx"
}

###
//ACTUALIZAR cliente
PUT  http://localhost:3000/clients/hola
Content-Type: application/json

{
"first_name": "cola",
"last_name": "PAPA",
"birth_date": "1990-01-01",
"gender":"M",
"phone_number": "11156789",
"email": "cola@gmail.com",
"address": "micasa"
}

//ELIMINAR 
###
DELETE  http://localhost:3000/clients/hola
