###
GET http://localhost:3000/products/


####
GET http://localhost:3000/products/3

//Agregar Producto
###
POST http://localhost:3000/products/
Content-Type: application/json

{
  "product": "Galleta",
  "description": "Galleta animalito",
  "stock": 70,
  "measurement_unit": "piece",
  "price": 25,
  "discount": 5
}

###
//ACTUALIZAR Producto
PUT  http://localhost:3000/products/5
Content-Type: application/json

{
  "product": "agua",
  "description": "refresco",
  "stock": 10,
  "measurement_unit": "piece",
  "price": 35,
  "discount": 5
  
}

//ELIMINAR 
###
DELETE  http://localhost:3000/products/3


