###
GET http://localhost:3000/clients/

//Mostrar por RFC #poner un RFC
###
GET http://localhost:3000/clients/hola

//Crear Cliente
###
POST http://localhost:3000/clients/
Content-Type: application/json

{
 "rfc": "RFC123456789",
  "first_name": "Nombre",
  "last_name": "Apellidos",
  "birth_date": "1990-05-20",
  "gender": "F",
  "phone_number": "5551234567",
  "email": "xxx@homtial.com",
  "address": "xxx"
}

###
//ACTUALIZAR cliente
PUT  http://localhost:3000/clients/RFC123456789
Content-Type: application/json

{
"first_name": "cola",
"last_name": "PAPA",
"birth_date": "1990-01-01",
"gender":"M",
"phone_number": "1234567890",
"email": "pp@gmail.com",
"address": "micasa"
}

//ELIMINAR 
###
DELETE  http://localhost:3000/clients/hola
