###
GET http://localhost:3000/staff/

####
GET http://localhost:3000/staff/1

//TAREA CREAR USUARIO
###
POST http://localhost:3000/staff/
Content-Type: application/json

{
"first_name": "John",
"last_name": "Doe",
"birth_date": "1990-01-01",
"gender":"M",
"phone_number": "123456789",
"email": "Johlldoe@gmail.com",
"address": "123 Main St. New York",
"user_id": 1
}


###
//ACTUALIZAR USUARIO
PUT  http://localhost:3000/staff/2
Content-Type: application/json

{
"first_name": "popamapkl",
"last_name": "PAPA",
"birth_date": "1990-01-01",
"gender":"M",
"phone_number": "123456789",
"email": "Johndoe@gmail.com",
"address": "123 Main St. New York",
"user_id": 1
}

//ELIMINAR 
###
DELETE  http://localhost:3000/staff/1
