###
GET http://localhost:3000/users/

###
GET http://localhost:3000/users/1

###
POST http://localhost:3000/users/
Content-Type: application/json
{
  "username": "Monserrat",
  "password": "mon123",
  "email": "mon@gmail.com"
}


###
PUT http://localhost:3000/users/1
Content-Type: application/json
  {
    "username": "mooonn"
  }

###
POST http://localhost:3000/users/login
Content-Type: application/json
  {
    "username": "Monserrat",
    "password": "mon123"
  }

###
DELETE http://localhost:3000/users/2


### Mostrar todo staff
GET http://localhost:3000/staff

### Mostrar staff por ID
GET http://localhost:3000/staff/2

### Agregar a staff
POST http://localhost:3000/staff
Content-Type: application/json

{
  "first_name": "Monse",
  "last_name": "Caba",
  "birth_date": "2003-10-17",
  "gender": "F",
  "phone_number": "2871053008",
  "email": "mon@gmail.com",
  "address": "Av 5 de mayo",
  "user_id": 2,
  "is_active": true,
}

### Actualizar staff
PUT http://localhost:3000/staff/1
Content-Type: application/json
  {
    "first_name": "Monse",
    "last_name": "Caba",
    "birth_date": "2003-10-17",
    "gender": "F",
    "phone_number": "2871053008",
    "email": "mon@gmail.com",
    "address": "Av 5 de mayo",
    "user_id": 3
  }

### Eliminar staff 
DELETE http://localhost:3000/staff/3